### ISSUE TITLE
Python and g++ versions used in `alfa-python`

### ISSUE THREAD

**Issue by pcotret** [castacks/alfa-dataset-tools#6]
I got a behavior similar to https://github.com/castacks/alfa-dataset-tools/issues/3

```
[ 60%] Performing build step for 'Boost'
Performing configuration checks

    - default address-model    : 64-bit
    - default architecture     : x86

Component configuration:

    - atomic                   : not building
    - chrono                   : not building
    - container                : not building
    - context                  : not building
    - contract                 : not building
    - coroutine                : not building
    - date_time                : not building
    - exception                : not building
    - fiber                    : not building
    - filesystem               : not building
    - graph                    : not building
    - graph_parallel           : not building
    - headers                  : not building
    - iostreams                : not building
    - locale                   : not building
    - log                      : not building
    - math                     : not building
    - mpi                      : not building
    - nowide                   : not building
    - program_options          : not building
    - python                   : building
    - random                   : not building
    - regex                    : not building
    - serialization            : not building
    - stacktrace               : not building
    - system                   : not building
    - test                     : not building
    - thread                   : not building
    - timer                    : not building
    - type_erasure             : not building
    - wave                     : not building

In file included from ./boost/python/detail/is_xxx.hpp:8,
                 from ./boost/python/detail/is_auto_ptr.hpp:9,
                 from ./boost/python/detail/copy_ctor_mutates_rhs.hpp:8,
                 from ./boost/python/detail/value_arg.hpp:7,
                 from ./boost/python/object/forward.hpp:10,
                 from ./boost/python/object/pointer_holder.hpp:16,
                 from ./boost/python/to_python_indirect.hpp:10,
                 from ./boost/python/converter/arg_to_python.hpp:10,
                 from ./boost/python/call.hpp:15,
                 from ./boost/python/object_core.hpp:14,
                 from ./boost/python/object.hpp:9,
                 from ./boost/python/exec.hpp:8,
                 from libs/python/src/exec.cpp:6:
./boost/python/detail/is_auto_ptr.hpp:17:40: warning: ‘template<class> class std::auto_ptr’ is deprecated: use 'std::unique_ptr' instead [-Wdeprecated-declarations]
   17 | BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
      |                                        ^~~~~~~~
./boost/detail/is_xxx.hpp:20:4: note: in definition of macro ‘BOOST_DETAIL_IS_XXX_DEF’
   20 |    qualified_name< BOOST_PP_ENUM_PARAMS_Z(1, nargs, T) >        \
      |    ^~~~~~~~~~~~~~
./boost/python/detail/is_auto_ptr.hpp:17:1: note: in expansion of macro ‘BOOST_PYTHON_IS_XXX_DEF’
   17 | BOOST_PYTHON_IS_XXX_DEF(auto_ptr, std::auto_ptr, 1)
      | ^~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/11/memory:76,
                 from ./boost/config/no_tr1/memory.hpp:21,
                 from ./boost/get_pointer.hpp:14,
                 from ./boost/python/object/pointer_holder.hpp:11,
                 from ./boost/python/to_python_indirect.hpp:10,
                 from ./boost/python/converter/arg_to_python.hpp:10,
                 from ./boost/python/call.hpp:15,
                 from ./boost/python/object_core.hpp:14,
                 from ./boost/python/object.hpp:9,
                 from ./boost/python/exec.hpp:8,
                 from libs/python/src/exec.cpp:6:
/usr/include/c++/11/bits/unique_ptr.h:57:28: note: declared here
   57 |   template<typename> class auto_ptr;
      |                            ^~~~~~~~
In file included from ./boost/preprocessor/iteration/detail/iter/forward1.hpp:47,
                 from ./boost/python/call.hpp:33,
                 from ./boost/python/object_core.hpp:14,
                 from ./boost/python/object.hpp:9,
                 from ./boost/python/exec.hpp:8,
                 from libs/python/src/exec.cpp:6:
./boost/python/call.hpp: In function ‘typename boost::python::detail::returnable<T>::type boost::python::call(PyObject*, boost::type<T>*)’:
./boost/python/call.hpp:62:28: warning: ‘PyObject* PyEval_CallFunction(PyObject*, const char*, ...)’ is deprecated [-Wdeprecated-declarations]
   62 |     PyObject* const result =
      |         ~~~~~~~~~~~~~~~~~~~^
   63 |         PyEval_CallFunction(
      |         ~~~~~~~~~~~~~~~~~~~~
   64 |             callable
      |             ~~~~~~~~        
   65 |             , const_cast<char*>("(" BOOST_PP_REPEAT_1ST(N, BOOST_PYTHON_FIXED, "O") ")")
      |             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   66 |             BOOST_PP_REPEAT_1ST(N, BOOST_PYTHON_FAST_ARG_TO_PYTHON_GET, nil)
      |             ~               
In file included from /usr/include/python3.10/Python.h:130,
                 from ./boost/python/detail/wrap_python.hpp:178,
                 from ./boost/python/detail/prefix.hpp:13,
                 from ./boost/python/ssize_t.hpp:9,
                 from ./boost/python/object.hpp:8,
                 from ./boost/python/exec.hpp:8,
                 from libs/python/src/exec.cpp:6:
/usr/include/python3.10/ceval.h:26:43: note: declared here
   26 | Py_DEPRECATED(3.9) PyAPI_FUNC(PyObject *) PyEval_CallFunction(
      |                                           ^~~~~~~~~~~~~~~~~~~
libs/python/src/exec.cpp: In function ‘boost::python::api::object boost::python::exec_file(const char*, boost::python::api::object, boost::python::api::object)’:
libs/python/src/exec.cpp:109:14: error: ‘_Py_fopen’ was not declared in this scope; did you mean ‘_Py_wfopen’?
  109 |   FILE *fs = _Py_fopen(f, "r");
      |              ^~~~~~~~~
      |              _Py_wfopen
```

As it seems to be an issue somewhere in a C++ file, i assume the issue is about Python and/or g++ versions used.
- Python 3.10
- g++ 11

What was your setup to play with the ALFA dataset ?

**Comment by pcotret** [comment]
Solved, works with Python 3.9 or older.
